/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: '#07070b',
        'bg-2': '#0d0d14',
        surface: '#14141d',
        'surface-2': '#1c1c28',
        'surface-3': '#262635',
        'border-base': '#2a2a3a',
        'border-bright': '#3d3d52',
        'text-base': '#f2f2f7',
        'text-dim': '#8e8ea3',
        'text-mute': '#5a5a72',
        accent: '#d4ff3a',
        'accent-dim': '#9bbf28',
        correct: '#4ade80',
        'correct-bg': 'rgba(74, 222, 128, 0.12)',
        incorrect: '#f87171',
        'incorrect-bg': 'rgba(248, 113, 113, 0.12)',
        type: {
          normal: '#b8b888',
          fire: '#ff8a3c',
          water: '#6c9bff',
          electric: '#f8d038',
          grass: '#7fce5e',
          ice: '#9be0e8',
          fighting: '#e04848',
          poison: '#c060c0',
          ground: '#e8c878',
          flying: '#b8a0ff',
          psychic: '#ff70a0',
          bug: '#c2d228',
          rock: '#d0b048',
          ghost: '#9078c0',
          dragon: '#8e60ff',
          dark: '#8a6e58',
          steel: '#c8c8e0',
          fairy: '#f4aac0',
        },
      },
      fontFamily: {
        display: ['"RocknRoll One"', 'sans-serif'],
        body: ['"Zen Kaku Gothic New"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      letterSpacing: {
        wider2: '0.15em',
        widest2: '0.2em',
        widest3: '0.25em',
      },
    },
  },
  plugins: [],
};
